import { Link } from 'react-router-dom'
import Footer from '../components/Footer'

function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-white">
      <header className="border-b border-gray-200 bg-white">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
          <Link
            to="/"
            className="inline-flex items-center text-blue-600 font-semibold hover:text-blue-700 transition-colors"
          >
            ← Back to Schedulze
          </Link>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 md:py-16">
        <h1 className="text-3xl md:text-4xl font-bold text-gray-900 mb-2">
          Privacy Policy
        </h1>
        <p className="text-gray-600 mb-12">Last updated: January 29, 2026</p>

        <div className="prose-content space-y-10 text-gray-600">
          <p className="text-lg">
            This Privacy Policy describes Our policies and procedures on the collection,
            use and disclosure of Your information when You use the Service and tells You
            about Your privacy rights and how the law protects You.
          </p>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-6">
              Interpretation and Definitions
            </h2>
            <h3 className="text-xl font-semibold text-gray-800 mb-3">Interpretation</h3>
            <p className="mb-6">
              The words whose initial letters are capitalized have meanings defined under
              the following conditions. The following definitions shall have the same
              meaning regardless of whether they appear in singular or in plural.
            </p>
            <h3 className="text-xl font-semibold text-gray-800 mb-4">Definitions</h3>
            <p className="mb-4">For the purposes of this Privacy Policy:</p>
            <ul className="space-y-2 mb-6">
              {[
                'Account means a unique account created for You to access our Service or parts of our Service.',
                'Affiliate means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
                'Company (referred to as either "the Company", "We", "Us" or "Our" in this Privacy Policy) refers to Techitenge Limited, Park Road, Entebbe, Uganda.',
                'Cookies are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.',
                'Country refers to: Uganda',
                'Device means any device that can access the Service such as a computer, a cell phone or a digital tablet.',
                'Personal Data (or "Personal Information") is any information that relates to an identified or identifiable individual. We use "Personal Data" and "Personal Information" interchangeably unless a law uses a specific term.',
                'Service refers to the Website.',
                'Service Provider means any natural or legal person who processes the data on behalf of the Company.',
                'Usage Data refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.',
                'Website refers to Schedulze, accessible from https://schedulze.com.',
                'You means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
              ].map((item, i) => (
                <li key={i} className="flex items-start">
                  <span className="text-red-500 mr-2">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-6">
              Collecting and Using Your Personal Data
            </h2>
            <h3 className="text-xl font-semibold text-gray-800 mb-4">Types of Data Collected</h3>
            <h4 className="text-lg font-semibold text-gray-800 mb-2">Personal Data</h4>
            <p className="mb-4">
              While using Our Service, We may ask You to provide Us with certain personally
              identifiable information that can be used to contact or identify You.
              Personally identifiable information may include, but is not limited to:
            </p>
            <ul className="space-y-2 mb-6">
              {['Email address', 'First name and last name', 'Phone number'].map((item, i) => (
                <li key={i} className="flex items-start">
                  <span className="text-red-500 mr-2">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <h4 className="text-lg font-semibold text-gray-800 mb-2">Usage Data</h4>
            <p className="mb-4">
              Usage Data is collected automatically when using the Service. Usage Data may
              include information such as Your Device's Internet Protocol address (e.g. IP
              address), browser type, browser version, the pages of our Service that You
              visit, the time and date of Your visit, the time spent on those pages, unique
              device identifiers and other diagnostic data.
            </p>
            <h4 className="text-lg font-semibold text-gray-800 mb-2">Tracking Technologies and Cookies</h4>
            <p className="mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our
              Service and store certain information. We use Session and Persistent Cookies
              for purposes such as necessary/essential cookies, cookies policy/notice
              acceptance, and functionality cookies. Where required by law, we use
              non-essential cookies only with Your consent.
            </p>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-800 mb-4">Use of Your Personal Data</h3>
            <p className="mb-4">The Company may use Personal Data for the following purposes:</p>
            <ul className="space-y-2 mb-6">
              {[
                'To provide and maintain our Service, including to monitor the usage of our Service.',
                'To manage Your Account and registration as a user of the Service.',
                'For the performance of a contract through the Service.',
                'To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.',
                'To provide You with news, special offers, and general information about other goods, services and events which We offer.',
                'To manage Your requests to Us.',
                'For business transfers: We may use Your Personal Data to evaluate or conduct a merger, divestiture, restructuring, or other sale or transfer of some or all of Our assets.',
                'For other purposes such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service.',
              ].map((item, i) => (
                <li key={i} className="flex items-start">
                  <span className="text-red-500 mr-2">•</span>
                  <span>{item}</span>
                </li>
              ))}
            </ul>
            <p className="mb-4">We may share Your Personal Data with Service Providers, in connection with business transfers, with Affiliates, with business partners, with other users where applicable, or with Your consent.</p>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-800 mb-4">Retention of Your Personal Data</h3>
            <p className="mb-4">
              The Company will retain Your Personal Data only for as long as is necessary
              for the purposes set out in this Privacy Policy. We apply different retention
              periods to different categories of Personal Data (e.g. Account Information,
              Customer Support Data, Usage Data). You may request information about how
              long We will retain Your Personal Data by contacting Us.
            </p>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-800 mb-4">Transfer of Your Personal Data</h3>
            <p className="mb-4">
              Your information, including Personal Data, is processed at the Company's
              operating offices and in any other places where the parties involved in the
              processing are located. Where required by applicable law, We will ensure
              that international transfers of Your Personal Data are subject to
              appropriate safeguards.
            </p>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-800 mb-4">Delete Your Personal Data</h3>
            <p className="mb-4">
              You have the right to delete or request that We assist in deleting the
              Personal Data that We have collected about You. You may update, amend, or
              delete Your information at any time by signing in to Your Account or by
              contacting Us. We may need to retain certain information when we have a
              legal obligation or lawful basis to do so.
            </p>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-800 mb-4">Disclosure of Your Personal Data</h3>
            <p className="mb-4">
              The Company may disclose Your Personal Data in connection with business
              transactions (e.g. merger, acquisition), if required by law or in response
              to valid requests by public authorities, or when necessary to comply with a
              legal obligation, protect and defend the rights or property of the Company,
              prevent or investigate possible wrongdoing, protect the personal safety of
              Users or the public, or protect against legal liability.
            </p>
          </section>

          <section>
            <h3 className="text-xl font-semibold text-gray-800 mb-4">Security of Your Personal Data</h3>
            <p className="mb-4">
              The security of Your Personal Data is important to Us, but no method of
              transmission over the Internet or method of electronic storage is 100%
              secure. While We strive to use commercially reasonable means to protect
              Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-6">
              Children's Privacy
            </h2>
            <p className="mb-4">
              Our Service does not address anyone under the age of 16. We do not knowingly
              collect personally identifiable information from anyone under the age of 16.
              If You are a parent or guardian and You are aware that Your child has
              provided Us with Personal Data, please contact Us.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-6">
              Links to Other Websites
            </h2>
            <p className="mb-4">
              Our Service may contain links to other websites that are not operated by Us.
              We strongly advise You to review the Privacy Policy of every site You visit.
              We have no control over and assume no responsibility for the content, privacy
              policies or practices of any third party sites or services.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-6">
              Changes to this Privacy Policy
            </h2>
            <p className="mb-4">
              We may update Our Privacy Policy from time to time. We will notify You of any
              changes by posting the new Privacy Policy on this page and updating the "Last
              updated" date at the top. You are advised to review this Privacy Policy
              periodically for any changes.
            </p>
          </section>

          <section>
            <h2 className="text-2xl md:text-3xl font-bold text-gray-900 mb-6">
              Contact Us
            </h2>
            <p className="mb-4">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <ul className="space-y-2">
              <li className="flex items-start">
                <span className="text-red-500 mr-2">•</span>
                <span>By email: <a href="mailto:joshua.waiswa@schedulze.com" className="text-blue-600 hover:text-blue-700 underline">joshua.waiswa@schedulze.com</a></span>
              </li>
              <li className="flex items-start">
                <span className="text-red-500 mr-2">•</span>
                <span>By phone: <a href="tel:+256771806549" className="text-blue-600 hover:text-blue-700 underline">+256771806549</a></span>
              </li>
            </ul>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  )
}

export default PrivacyPolicy
